import { SentiMood } from '../types';

export const SentiAvatars: Record<SentiMood, any> = {
  '01_happy': require('../../assets/mascot/avatar/01_happy.png'),
  '02_sad': require('../../assets/mascot/avatar/02_sad.png'),
  '03_excited': require('../../assets/mascot/avatar/03_excited.png'),
  '04_wink': require('../../assets/mascot/avatar/04_wink.png'),
  '05_love': require('../../assets/mascot/avatar/05_love.png'),
  '06_laughing': require('../../assets/mascot/avatar/06_laughing.png'),
  '07_blushing': require('../../assets/mascot/avatar/07_blushing.png'),
  '08_cool': require('../../assets/mascot/avatar/08_cool.png'),
  '09_curious': require('../../assets/mascot/avatar/09_curious.png'),
  '10_thinking': require('../../assets/mascot/avatar/10_thinking.png'),
  '11_surprised': require('../../assets/mascot/avatar/11_surprised.png'),
  '12_confused': require('../../assets/mascot/avatar/12_confused.png'),
  '13_sleepy': require('../../assets/mascot/avatar/13_sleepy.png'),
  '14_tired': require('../../assets/mascot/avatar/14_tired.png'),
  '15_angry': require('../../assets/mascot/avatar/15_angry.png'),
  '16_proud': require('../../assets/mascot/avatar/16_proud.png'),
  '17_shy': require('../../assets/mascot/avatar/17_shy.png'),
  '18_embarrassed': require('../../assets/mascot/avatar/18_embarrassed.png'),
  '19_working': require('../../assets/mascot/avatar/19_working.png'),
  '20_celebrating': require('../../assets/mascot/avatar/20_celebrating.png'),
  '21_relaxed': require('../../assets/mascot/avatar/21_relaxed.png'),
  '22_eating': require('../../assets/mascot/avatar/22_eating.png'),
  '23_idea': require('../../assets/mascot/avatar/23_idea.png'),
  '24_good_night': require('../../assets/mascot/avatar/24_good_night.png'),
};

export const SentiBadges: Record<SentiMood, any> = {
  '01_happy': require('../../assets/mascot/badge/01_happy.png'),
  '02_sad': require('../../assets/mascot/badge/02_sad.png'),
  '03_excited': require('../../assets/mascot/badge/03_excited.png'),
  '04_wink': require('../../assets/mascot/badge/04_wink.png'),
  '05_love': require('../../assets/mascot/badge/05_love.png'),
  '06_laughing': require('../../assets/mascot/badge/06_laughing.png'),
  '07_blushing': require('../../assets/mascot/badge/07_blushing.png'),
  '08_cool': require('../../assets/mascot/badge/08_cool.png'),
  '09_curious': require('../../assets/mascot/badge/09_curious.png'),
  '10_thinking': require('../../assets/mascot/badge/10_thinking.png'),
  '11_surprised': require('../../assets/mascot/badge/11_surprised.png'),
  '12_confused': require('../../assets/mascot/badge/12_confused.png'),
  '13_sleepy': require('../../assets/mascot/badge/13_sleepy.png'),
  '14_tired': require('../../assets/mascot/badge/14_tired.png'),
  '15_angry': require('../../assets/mascot/badge/15_angry.png'),
  '16_proud': require('../../assets/mascot/badge/16_proud.png'),
  '17_shy': require('../../assets/mascot/badge/17_shy.png'),
  '18_embarrassed': require('../../assets/mascot/badge/18_embarrassed.png'),
  '19_working': require('../../assets/mascot/badge/19_working.png'),
  '20_celebrating': require('../../assets/mascot/badge/20_celebrating.png'),
  '21_relaxed': require('../../assets/mascot/badge/21_relaxed.png'),
  '22_eating': require('../../assets/mascot/badge/22_eating.png'),
  '23_idea': require('../../assets/mascot/badge/23_idea.png'),
  '24_good_night': require('../../assets/mascot/badge/24_good_night.png'),
};
